#!/bin/bash


read -p "Enter the first number: " num1


read -p "Enter the second number: " num2


echo "Choose an arithmetic operation:"
echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Division"


read -p "Enter your choice (1/2/3/4): " choice


case $choice in
  1) echo "Result of addition: $((num1 + num2))" ;;
  2) echo "Result of subtraction: $((num1 - num2))" ;;
  3) echo "Result of multiplication: $((num1 * num2))" ;;
  4)
    if [ $num2 -ne 0 ]; then
      echo "Result of division: $((num1 / num2))"
    else
      echo "Error: Division by zero is not allowed."
    fi
    ;;
  *) echo "Invalid choice. Please enter 1, 2, 3, or 4." ;;
esac

