#!/bin/bash


current_date_time=$(date)
username=$(whoami)

current_directory=$(pwd)


echo "Current Date and Time: $current_date_time"
echo "Username: $username"
echo "Current Working Directory: $current_directory"
