#!/bin/bash


echo "Enter the number of terms: " n
read n

a=0
b=1

echo "Fibonacci series up to $n terms:"


for (( i=0; i<n; i++ ))
do
  echo -n "$a "
  next=$((a + b))
  a=$b
  b=$next
done

echo

